# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-DirList
version:      0.02
version_from: lib/File/DirList.pm
installdirs:  site
requires:
    DirHandle:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
